### ISSUE TITLE
Axolotl play dead effect broken

### ISSUE THREAD

**Issue by Neppkun** [TheLimeGlass/Khoryl#23]
I've attached a gifand an image, the video's code is as follows:
```vbs
command /wow:
	trigger:
		loop all entities in radius 3 of player:
			loop-entity is an axolotl:
				set playing dead of loop-entity to true
```
which loads without errors but you can see that the axolotl only tilts slightly (which I'm assuming is the playing dead animation starting) but doesn't continue and the state of the axolotl resets.

The picture's code is same as above except using `make loop-entity play dead` instead which makes it so Skript can't register the command for some reason... here's a pastebin link of the error that shows up in console when I try to reload the skript file: https://pastebin.com/adaD55i1.

My server is running on Paper 1.19 with 1.0.7-PRE Khoryl and 2.6.3 Skript.

Please let me know if you need any more info!

![javaw_YWi4Oh7XUp](https://user-images.githubusercontent.com/57060018/180976539-60c8ce8a-f739-4f43-8ec2-a057d2785acd.png)
![javaw_XKmkr8fjv9](https://user-images.githubusercontent.com/57060018/180977096-1a267aca-9a8f-4489-b626-4d48dfa91fc1.gif)

**Comment by TheLimeGlass** [comment]
From Spigot's JavaDoc: 'An axolotl may play dead when it is damaged underwater.'

So it has to be damaged and underwater for it to play the effect.
