### ISSUE TITLE
effect drop is no working . 

### ISSUE THREAD

**Issue by Tonipop** [TheLimeGlass/Khoryl#28]
in version 1.18 my skripts were 
Skript  2.6.3
SkQuery v4.1.7
Khoryl-1.0.6 
I used the effect drop 1 stone 
but it didnt worked , until when I unistalled Khoryl-1.0.6 , and found the issue

can you pls fix it.

**Comment by TheLimeGlass** [comment]
Not Khoryl. No errors provided.
